/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as PassportRouteImport } from './routes/passport'
import { Route as MuseumRouteImport } from './routes/museum'
import { Route as CinemaRouteImport } from './routes/cinema'
import { Route as IndexRouteImport } from './routes/index'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportRoute = PassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => rootRouteImport,
} as any)
const MuseumRoute = MuseumRouteImport.update({
  id: '/museum',
  path: '/museum',
  getParentRoute: () => rootRouteImport,
} as any)
const CinemaRoute = CinemaRouteImport.update({
  id: '/cinema',
  path: '/cinema',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cinema': typeof CinemaRoute
  '/museum': typeof MuseumRoute
  '/passport': typeof PassportRoute
  '/quiz': typeof QuizRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cinema': typeof CinemaRoute
  '/museum': typeof MuseumRoute
  '/passport': typeof PassportRoute
  '/quiz': typeof QuizRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cinema': typeof CinemaRoute
  '/museum': typeof MuseumRoute
  '/passport': typeof PassportRoute
  '/quiz': typeof QuizRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cinema' | '/museum' | '/passport' | '/quiz' | '/timeline'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cinema' | '/museum' | '/passport' | '/quiz' | '/timeline'
  id:
    | '__root__'
    | '/'
    | '/cinema'
    | '/museum'
    | '/passport'
    | '/quiz'
    | '/timeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CinemaRoute: typeof CinemaRoute
  MuseumRoute: typeof MuseumRoute
  PassportRoute: typeof PassportRoute
  QuizRoute: typeof QuizRoute
  TimelineRoute: typeof TimelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport': {
      id: '/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof PassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/museum': {
      id: '/museum'
      path: '/museum'
      fullPath: '/museum'
      preLoaderRoute: typeof MuseumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cinema': {
      id: '/cinema'
      path: '/cinema'
      fullPath: '/cinema'
      preLoaderRoute: typeof CinemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CinemaRoute: CinemaRoute,
  MuseumRoute: MuseumRoute,
  PassportRoute: PassportRoute,
  QuizRoute: QuizRoute,
  TimelineRoute: TimelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
